# Generated by Django 3.2 on 2022-12-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('message_date', models.DateTimeField(auto_now_add=True)),
                ('message_subject', models.CharField(max_length=400)),
                ('reply_sent', models.BooleanField(default=False)),
                ('regarding', models.CharField(choices=[('breakdown assist', 'Breakdown assist'), ('refunds', 'Refunds'), ('vouchers', 'Vouchers'), ('rental duration', 'Rental duration'), ('pickup or dropoff', 'Pickup or dropoff'), ('cars', 'Cars'), ('other reason', 'Other reason')], default='Select', max_length=24)),
            ],
        ),
    ]
