# Generated by Django 3.2 on 2022-12-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20221113_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='maintenance_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
