# Generated by Django 3.2 on 2022-12-11 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_rename_price_carlist_priceperday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewcar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewtext', models.TextField(blank=True, max_length=800)),
                ('reviewtitle', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stars', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.carlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
