# Generated by Django 3.2 on 2022-12-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_reviewcar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carlist',
            options={'verbose_name_plural': 'Car List'},
        ),
    ]
