# Generated by Django 3.2 on 2022-12-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_carlist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewcar',
            options={'verbose_name_plural': 'Car Reviews'},
        ),
    ]
